# Generated by Django 4.1.2 on 2022-11-10 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterForm',
            new_name='Register',
        ),
    ]
